defaults:
  - gs_params: fast
  - paths
  - forest_bv
  - frozen_lake_bv

verbose: True
threads: 16
seed: 658028
aws: False

forest_enable: True
frozen_lake_enable: False

plot: True
plot_old_results: False
old_results_path:
