forest:
  VI:
    gamma: 0.99
    epsilon: 0.01 # the convergence criterion
  PI:
    gamma: 0.99
    convergence_value: 0.01
  QLearning:
    gamma: 0.99
    alpha: 0.25
    alpha_decay: 0.999
    epsilon_decay: 0.99
    epsilon_min: 0.02
    convergence_value: 0.001
    epsilon_decay_values: [0.9999, 0.999, 0.99, 0.9, 0.8]
    max_iterations: 20000
    #epsilon_decay_values: [0.999, 0.8]
