frozen_lake:
  VI:
    gamma: 0.99
    epsilon: 0.0001 # convergence threshold
  PI:
    gamma: 0.99
  QLearning:
    gamma: 0.99
    alpha: 0.25
    alpha_decay: 1
    epsilon_decay: 0.99
    epsilon_min: 0.1
    convergence_value: 0.0001
    epsilon_decay_values: [0.9999, 0.999, 0.99, 0.9, 0.8]
